model:
  type: t5
  name: ktoivola/mt5-small-finetuned-dialogsum-ko

data:
  encoder_max_len: 896
  decoder_max_len: 80

train:
  learning_rate: 3.0e-5
  batch_size: 8
  num_train_epochs: 12
  fp16: false
  early_stopping_patience: 4

style_prompt: null

paths:
  checkpoint_dir: checkpoints/kot5-base
  prediction_dir: prediction

wandb:
  use_wandb: false
  project: aistages-nlp-3
  run_name: kot5-base
