model:
  type: kobart
  name: gogamza/kobart-base-v1

data:
  encoder_max_len: 1024
  decoder_max_len: 80

train:
  learning_rate: 3.0e-5
  batch_size: 8
  num_train_epochs: 12
  fp16: true

style_prompt: null

paths:
  checkpoint_dir: checkpoints/kobart-base
  prediction_dir: prediction

wandb:
  use_wandb: false
  project: aistages-nlp-3
  run_name: kobart-base-sft
