model:
  type: t5
  name: google/mt5-small

data:
  encoder_max_len: 768
  decoder_max_len: 80

train:
  learning_rate: 3.0e-5
  batch_size: 8
  num_train_epochs: 5
  fp16: true

style_prompt: null

paths:
  checkpoint_dir: checkpoints/mt5-small
  prediction_dir: prediction

wandb:
  use_wandb: false
  project: aistages-nlp-3
  run_name: mt5-small

